plugins {
    id 'application'
}

application {
    mainClass = 'Main'
}

def lwjglNatives = 'natives-linux' // change to natives-macos or natives-linux if needed

repositories {
    mavenCentral() // Add this
}

dependencies {
    // This replaces the need for the manual JAR file
    implementation fileTree(dir: 'lib', include: ['*.jar'])
}

